spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/local_schema
#    username: root
#    password: qusghdud07!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jeollogamysql.cl2mgmwa8yhl.ap-northeast-2.rds.amazonaws.com:3306/JeollogaMySQL
    username: root
    password: Jeolloga1221
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: c88bbc64d675626c042b09adf00ef365
            client-secret: Wf8xoGP7Hrbu8B9CsJ3e6h1ETV3YnAQU
            client-authentication-method: client_secret_post
            authorization-grant-type : authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#logging:
#  level:
#    org.springframework.security: DEBUG

jwt:
  access-token-secret: thisIsJeollogaAccessTokenSecretKeyHowAboutThat
  refresh-token-secret: thisIsJeollogaRefreshTokenSecretKeyHowAboutThat

naver:
  api:
    client-id: kwWkZv4rtI3mEdO04fAR
    client-secret: yBTo19o1kx